"""update product coupon application

Revision ID: 6b187a499237
Revises: 
Create Date: 2025-06-25 01:03:14.353856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b187a499237'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_coupon_applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discount_percentage', sa.Float(), nullable=True))
        batch_op.alter_column('coupon_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('unique_product_coupon_active'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_coupon_applications', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('unique_product_coupon_active'), ['product_id', 'coupon_id'])
        batch_op.alter_column('coupon_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('discount_percentage')

    # ### end Alembic commands ###
